### ISSUE TITLE
I can not install it in Windows Server 2008 R2 x64?

### ISSUE THREAD

**Issue by afimpel** [leecher1337/ntvdmx64#14]
It is windows server standard edition without any additional service pack.
I have all the other packages intalado but this does not work for me.
That I have a software developed in foxpro, by a provider.

Thank you.
Alvaro.

**Comment by leecher1337** [comment]
This is currently for Windows 10 only, sorry. The reason behind this is that the processing function for invalid Images, which in turn kicks in NTVDM if it is a DOS-Application, is not exported from the KERNEL32.DLL on earlier versions and therefore it is much harder to intercept it.
I tried to write some code for interception, but it didn't turn out to be very stable atm. and may cause your Windows to lock up, so I didn't release it yet.
Additionally some Win10-specific adaptions to NTVDM may also need to be changed for earlier Windows versions, that's why it currently only works on Win10.

Btw.: I suggest that you use a 32bit Windows Server version if you want to run DOS-applications for multiple users. The reason for this is that ntvdmx64 build uses CPU-emulation ine DOSbox also does, but using V86 mode would be far more efficient in terms of CPU load, but is only possilble in 32bit protected mode.

**Comment by leecher1337** [comment]
Hi,
NTVDMX64 now also works with Windows 7, this may increase chance that it now also works with Windows Server 2008 as well, can you check it?

**Comment by juckdo** [comment]
![11](https://user-images.githubusercontent.com/19239966/36349442-5d7ebe74-14ca-11e8-8583-2c2decba34e2.png)

NTVDMx64 is works with Windows Server 2008 R2 x64 properly ..

**Comment by juckdo** [comment]
![36349467-0ba24e12-14cb-11e8-92a0-0e50a2964a91](https://user-images.githubusercontent.com/19239966/36349809-cac17788-14cf-11e8-9904-8ee89d813404.png)

NTVDMx64 is works with Windows Server 2008 R2 x64 properly ..

**Comment by ohharsad** [comment]
![error](https://user-images.githubusercontent.com/20744213/48841453-75302180-edcc-11e8-8429-83c5001cee8e.png)

I have this kind of error on Windows Server 2008 R2. any tips?

**Comment by leecher1337** [comment]
Does new loader fix the issue?

**Comment by ohharsad** [comment]
> Does new loader fix the issue?

sorry for the late reply, 
DbgView not showing anything, Actually i want to run a process from oracle form 6i that will run ntvdm.
but i will try this solution. 
https://github.com/leecher1337/ntvdmx64/issues/28#issuecomment-443469998

**Comment by leecher1337** [comment]
Assuming fixed with new loader, of not, reopen.
