### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [leecher1337/ntvdmx64#145]
i have question: How to uninstall NTVDMx64 ? i have installed it but its broken , i want to uninstall it, how can i do it?

**Comment by emendelson** [comment]
The same way you uninstall any other Windows application: in the list of apps in the Settings app.

**Comment by Siddhant-Mashalkar** [comment]
ok

**Comment by Siddhant-Mashalkar** [comment]
i just uninstalled, Ldntvdm.dll is still present and open in winlogon.exe, how to remove?

**Comment by leecher1337** [comment]
Remove ldntvdm.dll entry from Key AppInit_DLLs in the following 2 locations:

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Windows

**Comment by Siddhant-Mashalkar** [comment]
ok

**Comment by Siddhant-Mashalkar** [comment]
i modified registry keys and deleted the dll
but i have problem with cmd and cmd-like applications have changed, i could press alt-enter to enter fullscreen but alt-enter doesn't work
and ctrl-a , ctrl-v dont select or paste
how can i restore original cmd
i am running Windows 10 Version 1909 (UEFI)

**Comment by Siddhant-Mashalkar** [comment]
*and secure boot is disabled

**Comment by leecher1337** [comment]
ALT+ENTER Fullscreen doesn't work anymore since Windows 7. This is due to the change of the display driver model from XPDM to WDDM, which doesn't support 1:1 IO pass-through anymore.
On Windows 7 32bit, this can be fixed with a few tricks, but starting with Windows 8, XPDM support was eliminated from the kernel and thus, it's technically impossible.
So you have to stick with Windows XP or Windows 7 32bit for true Fullscreen support.
NB: Fullscreen support never worked on 64bit Windows versions, because IO-Bitmap cannot be modified on 64bit Windows versions.
I'm note aware of CTRL+A, c, v working on cmd, as keys get passed to the running application (which is correct behaviour)

**Comment by Siddhant-Mashalkar** [comment]
ok

**Comment by Siddhant-Mashalkar** [comment]
closing issue , i will reinstall windows now to fix some things
