### ISSUE TITLE
How to uninstall NTVDMx64 manually?

### ISSUE THREAD

**Issue by 0130smart** [leecher1337/ntvdmx64#199]
Hi. I can't find NTVDMx64 in Control Panel/Software. Seems like setup was not complete normally. How can I uninstall NTVDMx64 by myself? Or, Could you make something like force uninstaller?

**Comment by leecher1337** [comment]
Generally, uninstaller entry in control panel just calls:

`RunDll32 advpack.dll,LaunchINFSection ntvdmx64.Inf,DefaultUninstall`

Works, as long as .inf has been copied to global inf directory during installation.
Possibly also works directly on the ntvdmx64.Inf file shipped with the setup package, if not present in System inf directory,  as long as install.bat has been copied to Windows\Symbols\instntvdmx64.bat (so that it in in the location that the installer expects in order to call it).

In order to manually remove just the loader (that's the only thing that 'hurts' your system, the files that are possibly present in the system directory usually won't cause troubles and will be overwritten on next install on NTVDMx64), just rename ldntvdm.dll in both windows\system32 and windows\syswow64 dirtectory to a different name, so that they won't get loaded again on next reboot. After reboot, the renamed files are not in use anymore and can be deleted.

**Comment by 0130smart** [comment]
Thank you. It works without any problem.
