### ISSUE TITLE
NTVDM64 blocks Windows search

### ISSUE THREAD

**Issue by komfort64** [leecher1337/ntvdmx64#235]
I installed ntvdm64  from "http://www.columbia.edu/~em36/ntvdmx64.html". After the reboot of the
pc the Windows search doesn't run. After uninstalling ntvdm64 the Windows search was o.k.

**Comment by Linden10** [comment]
I was experiencing the same problem as recent as June of this year, not knowing what's causing the issue.
I installed NTVDM64 back in February 2023 and windows search was working fine up until randomly it stopped working back in June, only finding out it stopped working two months later this August.

After analysing the dump files, I was able to find that NTVDM64 was the cause!
I wonder if there's a way to prevent Windows Search from accessing ldntvdm.dll so that it can proceed to work...

Glad to find someone else who had the same problem!

**Comment by leecher1337** [comment]
Refer to https://github.com/leecher1337/ntvdmx64/issues/196#issuecomment-1173059215 to crate a blacklist entry for the process that ldntvdm.dll is interfering with, maybe it helps...

**Comment by Linden10** [comment]
> Refer to [#196 (comment)](https://github.com/leecher1337/ntvdmx64/issues/196#issuecomment-1173059215) to create a blacklist entry for the process that ldntvdm.dll is interfering with, maybe it helps...

Thank you! I just tried what you suggusted with the entry in ldntvdm.ini being:
`[blacklist]
SearchIndexer.exe`

and put it in C:\Windows and after that, started up the search service and it worked without any issue!

Again thank you, now search works again! ^_^

**Comment by leecher1337** [comment]
Note: This particular problem has been adressed in https://github.com/leecher1337/ntvdmx64/commit/b5ebb0e2bc171d17265bd77708c3726928f5f014
