### ISSUE TITLE
ntvdmx64 not working

### ISSUE THREAD

**Issue by thewanderingtraderm** [leecher1337/ntvdmx64#239]
I installed ntvdmx64 but when can't run a dos application it says this app cant run on your pc

**Comment by leecher1337** [comment]
OS version? Debugview log? Symbols present?

**Comment by kllkradio** [comment]
From what I can surmise, after the most recent major update (KB5031354) for Windows 11 (22H2) on 10/10/23, NTVDMx64 has stopped running on my computer.  I reinstalled NTVDMx64 with the latest version to no avail.

Here is the error message that I get when I open up a DOS program:

![ntvdmx64 error1](https://github.com/leecher1337/ntvdmx64/assets/93634762/9931ecb3-d872-4dfe-b03c-740e59f11a3c)

When I install NTVDMx64, I get an error message:
[*] Trying to download necessary debug symbols
C:\WINDOWS\symbols\Backup\compobj.dll: Access is denied.

![ntvdmx64 error2](https://github.com/leecher1337/ntvdmx64/assets/93634762/3f5051e9-9022-4788-9098-e80efb715198)

My guess is that this is the problem.  It has been over seven days since Microsoft released the major update so I am beginning to think that KB5031354 may have broken something.

Any thoughts as to what can be done to correct this?  NTVDMx64 is fabulous!

**Comment by kllkradio** [comment]
Good News!  This evening, I installed the 2023-10 Cumulative Update Preview for Windows 11 Version 22H2 for x64-based Systems (KB5031455).  When my computer restarted, and I initiated a DOS program, I got an error stating that the program wasn't compatible with 64-bit operating systems.  This was a different error message than I had gotten previously.  I then uninstalled ntvdmx64 and reinstalled it.  I don't know why, but after reinstalling ntvdmx64 this time, my DOS programs started working again!
