### ISSUE TITLE
fatal sys err 10025: Unexpected processor exception occurred | Error Occurred in Protected mode,......

### ISSUE THREAD

**Issue by mlcindia** [leecher1337/ntvdmx64#26]
Hi Leecher1337,

I am using a foxpro 2.6 program which works using VDos and DosBox on Windows 10 64bit latest build 1803.
After install.bat, I rebooted the machine.
Then Ran My Program, which shows the following error.
Even now, If I am using DosBox, my program won't open.

Pls have a look at the Screenshot:
![ntvdm error](https://user-images.githubusercontent.com/42622257/44488130-9bcba880-a675-11e8-83fc-fc5838b4b3e4.PNG)

**Comment by leecher1337** [comment]
Hi,
Protected mode emulation of NTVDM is not really perfect, unfortunately.
Did you check if your application works in original NTVDM (on 32bit Windows)? Could be a general problem with NTVDM or a bug in NTVDMx64 build with its C-CPU, hard to tell. Without having the actual application for testing, it's not really possible to diagnose.

**Comment by leecher1337** [comment]
There have been improvements to the DPMI support since this ticket was opened. As I don't know your specific application and just confirmend that FoxPro itself works, I'm unable to process this ticket further, therefore ticket will get closed. If you still have problems, you need to upload an executable file that allows me to reproduce the problem and reopen the ticket.
