### ISSUE TITLE
Would running quake 1.x become possible one day? 

### ISSUE THREAD

**Issue by sudo-000** [leecher1337/ntvdmx64#260]
Would running Quake 1.06 in windows 10 x64 become possible someday?

**Comment by sudo-000** [comment]
Just saw the thing in your readme, mentioning something related to direct memory access? 
Well, I wonder if it's possible to just enforce quake to not use the direct memory access hack which could be a little bit slower but a lot safer and best of all compatible with windows NT!

**Comment by leecher1337** [comment]
It never used to work with NTVDM, as its DPMI host incompatible with Quake DPMI-Tricks.

But I  also don't see a point in doing so, NTVDMx64 is slow (HAXM build is only fast for textmode stuff, but performance is very bad for Video stuff and this also cannot be optimized due to the way, virtualization works, as already explained in various places), so it doesn't make a lot of sense to run Games with it.
The main advantage of NTVDM is that is it able to do a seamless interop between 32bit and 16bit Applications and allowing to use the extended DOS-functions to inteact with Windows that some applications rely on.
But for just running games, simply use DosBox-X, it's meant for games and does its job pretty well in this regard.

**Comment by sudo-000** [comment]
I understand. Thanks for your reply.
