### ISSUE TITLE
Suggestion: vDOS and DOSBOX code integration

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [leecher1337/ntvdmx64#29]
The NTVDM is not perfect, but integrating some of the code from DOSBOX and vDOS (another open source project) may help out in this regard significantly. In addition, because they are both open source, it would enable a gradual transition away from the reliance closed source code, and thereby make it easier to distribute a 64-bit version of NTVDM. You can learn more about vDOS at https://vdos.info

**Comment by leecher1337** [comment]
I know VDOS. If you want to have VDOS-features, use VDOS.
Making another DOSBOX derivate isn't the goal of this project, there are already plenty of them out there. The goal here is to resemble original Microsoft NTVDM as closely as possible on x64 (with all its woes).

The NTVDM is tightly integrated with system services and especially console, unlike DOSBOX and its derivates like VDOS, which use a totally different console (based on SDL), doesn't support VDD extensions, has a total different CPU-emulator, doesn't support BOPs which are an integral part of Windows' DOS-emulation, etc. So basically nothing to take from there...
But bugfixes for NTVDM code are welcome, of course...

A useful improvement would be the integration of HAXM VM to get rid of the slow CCPU and use real hardware emulation like traditional V86 mode on Intel CPUs, but it will be a lot of work, I could definitely need some help with that. Any volunteers?

Meanwhile I'm working on reconstructing NTVDM sourcecode from XP's NTVDM to get some features that weren't present in NT4 (i.e. SB 2.0 emulation) to get accurate updated NTVDM sourcecode.
Together with WINEVDM project (Briliant project for supporting 16 bit Windows applications, highly recommended), users should have a good 16bit experience on x64 machines.

Writing own code that isn't the original one by Microsoft doesn't make sense here, because we are facing the ReactOS-developer problem: Someone who has seen the original Microsoft Sourcecode is "tainted" and cannot contribute to ReactOS anymore.
Regarding distribution, https://github.com/leecher1337/ntvdmx64/issues/7 is a very reliable source.
