### ISSUE TITLE
Why not make this also like DOSBox  and vDOS

### ISSUE THREAD

**Issue by HomerBender77** [leecher1337/ntvdmx64#38]
Why not integrate vDOS and DOSBox code into NTVDM? It would be cool, because it would be like DOSBox and VDOS but integrated into the Windows shell. What good is it to keep the woes of Microsoft NTVDM? It would be cool to be able to play DOS games by launching the EXE program itself instead of launching DOSBox and then having to type in commands.

**Comment by Nable80** [comment]
If you ever tried reading DOSBox code, you'd know it's not easy to integrate it with anything at all.
I didn't try vDOS but I think it wouldn't be easy too.
In both cases it's not obvious whether any benefits can be obtained.

**Comment by leecher1337** [comment]
vDOS also inherited code from DosBox. 
There too many differences in the inner workings of NTVDM and DosBox to be able to effectively use any part of DosBox in NTVDM. For instance NTVDM uses a flat allocated memory buffer as DOS memory where the emulated CPU writes to in the correct order, whereas the DOSBox CPU relies on memory access functions to give you the correct piece of memory, but you cannot assume that you have a flat memory block. This makes it very, very hard to implement VT-x into DosBox (i.e. via haxm), whereas NTVDM has no problem in this regard, as it was already designed to work in V86 mode where this is necessary.

Nevertheless,due to the fact that a transition between VT-x emulation and i.e. usermode adapter emulation is very expensive and happens all the time, I stopped implementing HAXM into NTVDM for now, there is no performance gain because of this,without some tricks that I used for textmode it's even slower than with the CCPU. I may release the sources for the integration so that interested programmers can play around with it, if there is interest.

So the only thing I can offer here is to add an option to the loader (controlled by registry) that it executes a stub instead of ntvdm.exe which in turn launches your favourite DOS emulator, i.e. DosBox instead of the NTVDM.

**Comment by peter8777555** [comment]
>I can offer here is to add an option to the loader (controlled by registry) that it executes a stub instead of ntvdm.exe
How to do it ?

**Comment by leecher1337** [comment]
I would have to implement this first, currently there is no such option, therefore I asked if this would be interesting?

**Comment by peter8777555** [comment]
>I would have to implement this first, 
>currently there is no such option, 
>therefore I asked if this would be interesting?

I know what is different betten vDOS/DosBox/NTVDM.
Each has its own merits.
I prefer to NTVDM.

There is such option more better.
I have one question
Does the option launch your favourite DOS emulator on "the same" shell ?

EX:
Test.exe is a DOS program.

A.
Open a console 1 -> run Test.exe
The Test.exe in console 1.

Or

B.
Open a console 1 -> run Test.exe
Open NEW console 2 and the Test.exe in console 2.

**Comment by leecher1337** [comment]
That depends on the DOS emulator you would use. As far as I know, there are currently no DOS emulators that work on the same shell and no DOS emulators that are able to use the Windows console besides NTVDM. All I can do is to launch another executable instead of NTVDM.EXE, the rest is up to the author of the respective emulator.

**Comment by cracyc** [comment]
Takeda's msdos player does (http://takeda-toshiya.my.coocan.jp/msdos/index.html).  It doesn't support graphics mode though (I have my own fork noodling with this, far from perfect though https://github.com/cracyc/msdos-player)

**Comment by HomerBender77** [comment]
> (I have my own fork noodling with this, far from perfect though https://github.com/cracyc/msdos-player)

But I don't know how to compile it.
