### ISSUE TITLE
About genall.cmd

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#54]
Running:
w:\cdimg\envvars.cmd
w:\cdimg\genall.cmd

Generating ISO image ...
Scanning source tree complete (0 files in 3 directories)
Computing directory information complete
Image file is 53248 bytes
Writing 0 files in 3 directories to W:\cdimg\iso\NT45Wks.iso
100% complete
Final image file is 53248 bytes
Done.

Creating:
w:\cdimg\boot : contains 1 File.
w:\cdimg\comp : contains 612 Files(14.1 MB (14,876,672 bytes))
w:\cdimg\iso : contains 1 File. 

w:\cdimg\iso\NT45Wks.iso size 52KB(53248 bytes) ONLY ?

**Comment by leecher1337** [comment]
The buildfiles of ntvdmx64 don't build NT4/OpenNT completely, just specifically the NTVDM with modifications. You won't be able to get a working NT4 NTVDM when using ntvdmx64 patches either, because it adapts certain syscalls for the use in newer Windows versions (i.e. the patches in w10.patch) 
Therefore, refer to http://www.opennt.net (there is a link to the old archived website) to get build instructions for OpenNT.

**Comment by peter8777555** [comment]
Thank you for info.
