### ISSUE TITLE
Running UPX/RAR failed

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#56]
I can NOT run any UPX programs.
I can NOT run RAR program.

**Comment by leecher1337** [comment]
Should work now, please confirm

**Comment by peter8777555** [comment]
I have try 4/30/2020 build.
No.

[UPX_RAR.zip](https://github.com/leecher1337/ntvdmx64/files/4561309/UPX_RAR.zip)

**Comment by leecher1337** [comment]
I now recompiled the whole minnt to verify and it works fine here.
Note that UPC takes approx. 10 seconds to start up. And the rar exe in your .zip doesn'T work without the other files contained in the RAR SFX, I attached proper RAR sfx for you

[rarx393.zip](https://github.com/leecher1337/ntvdmx64/files/4561646/rarx393.zip)

**Comment by peter8777555** [comment]
No work here.

![a1](https://user-images.githubusercontent.com/29886853/80765008-8d38d280-8b74-11ea-9aef-bc7708288fe5.png)
![a2](https://user-images.githubusercontent.com/29886853/80765011-8e69ff80-8b74-11ea-8bd7-7d99ec812a7b.png)
![a3](https://user-images.githubusercontent.com/29886853/80765014-8f029600-8b74-11ea-8cbd-83900967a6c7.png)
![a4](https://user-images.githubusercontent.com/29886853/80765015-8f9b2c80-8b74-11ea-8178-801b8ffb0505.png)

**Comment by leecher1337** [comment]
These errors look familiar for build without https://github.com/leecher1337/ntvdmx64/commit/25e9b9b18f615346f8a313e84c354d3e145c50c2
Can you manually verify that your source got patched correctly and object files contain the latest patches? Maybe you have leftover object files from older builds..?

**Comment by peter8777555** [comment]
[ntvdmx64-master.zip](https://github.com/leecher1337/ntvdmx64/files/4561707/ntvdmx64-master.zip)
[dpmi.zip](https://github.com/leecher1337/ntvdmx64/files/4561709/dpmi.zip)

**Comment by leecher1337** [comment]
No, I mean, if your mvdm\softpc.new\base\ccpu386\c_main.c contains mentioned patch after you run patch.cmd and that you ensured to started off with a clean minnt\base directory and thus you don't have any old mvdm\softpc.new\base\ccpu386\objchk files (obviously you shouldn't when you started off with a clean mvdm directory)

**Comment by peter8777555** [comment]
I usually remove ALL files in C:\work.
So it should be not OLD files in C:\work.

**Comment by peter8777555** [comment]
Failed again.
It still not work here.

**Comment by leecher1337** [comment]
Patch seems ok, weird.. Maybe it's related to host OS or something? I tested on Windows 10.

**Comment by peter8777555** [comment]
I tested on Windows 7 X64.

**Comment by leecher1337** [comment]
Just tested my build under Win7 x64, also worked there. What's the size of your ntvdm.exe build? I have 1.416.704 bytes.
Dumb question but did you also verify that ntvdm.exe got replaced properly in your windows\syswow64 directory, in case you had an old verison installed?

**Comment by peter8777555** [comment]
![a1](https://user-images.githubusercontent.com/29886853/80769555-27524800-8b80-11ea-9f16-77b1607be39a.png)
![a2](https://user-images.githubusercontent.com/29886853/80769558-28837500-8b80-11ea-8f89-80b78d228090.png)

**Comment by leecher1337** [comment]
Doesn't surprise me that it crashes if you singlestep in a DOS Debugger over lmsw. If you want to debug DOS applications running in NTVDM, use Master YODA.
i.e. to do instruction tracing, setup YODA environment variables as descripbed in readme, then set a REG_SZ with name YODA and value 1 so that YODA calls you right on startup of NTVDM, then you can i.e. do a run trace:
```
tf c:\temp\trace.txt
s
t
c
```
But I'm running out of ideas why it doesn't work for you. 
* We ruled out bad compilation as you strated off with clean work Directory
* We ruled out bad patches, as I did a complete rebuild on my machine
* We ruled out bad NTVDM.EXE on Installation
* We ruled out Operating System as I also tested on Windows 7

Maybe we should wait for a new build on the emendelson site, so that we at least have the same ntvdm.exe files to compare?

**Comment by peter8777555** [comment]
Emendelson site usually has NO latest updated.
So i build DIY for latest updated.

**Comment by leecher1337** [comment]
I guess you also verified that ntvdm.exe in System32 Directory is a hard link to Syswow64 ntvdm.exe . This also sometimes is a problem, because when you once overwrite the ntvdm.exe in system32 directory, it gets unlinked and then you can theoretically have 2 different versions.

Generally a good idea to build yourself, but we just need something to compare if it boils down to build process or other issues.

(Here is my build, will delete it, as soon as you have it to compare)
[ntvdm.zip](https://github.com/leecher1337/ntvdmx64/files/4561997/ntvdm.zip)

**Comment by peter8777555** [comment]
Yes,you are right.
C:\Windows\System32 is OLD version.
I copy New version to C:\Windows\System32 and it works.

Suggestion:
install.bat always copy(Overwrite) files to C:\Windows\System32 AND C:\Windows\SysWOW64

By the way,
It is weired,
First run RAR32.exe is OK.
Second run RAR32.exe is NG ?

[RAR393.zip](https://github.com/leecher1337/ntvdmx64/files/4562121/RAR393.zip)

**Comment by leecher1337** [comment]
Latest DPMI fix requires you to update dosx.exe

**Comment by peter8777555** [comment]
Nice work and Thank you.
