### ISSUE TITLE
About HAXM

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#62]
I have finish to compile two versions.

Q1.
The ntvdm.exe file size is more small ??

3,252,496 ntvdm.exe (Old version)

1,515,280 ntvdm.exe (New version)
1,283,344 ntvdm.exe (New version with HAXM)

Q2.
Can not support Intel Core 2 Quad Q8400 for HAXM ??

OS : Windows 7 X64
CPU : Intel Core 2 Quad Q8400
RAM :  12 GB

HAXM_Check.exe
VT support -- yes
NX support -- yes

It seem has NO support EPT.

CPU-Z

![z1](https://user-images.githubusercontent.com/29886853/64995009-b457d200-d90c-11e9-9ea5-b677407f0ad1.png)

**Comment by leecher1337** [comment]
Ad 1)
It also depends on the directory where you pull the executable from (builds with debug symbols are bigger, for instance). But the new CVIDC that doesn't use the bloated generated code slims down the NTVDM a lot.
As there is no emulated CCPU in the HAXM build, this also is benificial in terms of executable size

Ad 2) That's a pity, but it seems to be correct that your CPU unfortunately doesn't support EPT and therefore cannot be used for HAXM:
https://community.spiceworks.com/topic/455835-virtualized-intel-vt-x-ept-is-not-supported-on-this-platform

EPT feature is required for HAXM and Unrestricted Guest (UG) feature is a requrement for NTVDMx64. Too bad, it would have been interesting for me the hear about usecases where VT-x would be beinificial (I only found data sorting in a DOS database application to be a good usecase for high accelleration copared to emulated CPU).

**Comment by peter8777555** [comment]
Thank you for detail info.

1.
How many percent speed up with HAXM ?

2.
My CPU can not support HAXM,
Maybe NTVDMX64 can speed up for FPU/Video.

NTVDMX64
![1](https://user-images.githubusercontent.com/29886853/65024776-11cd3c80-d968-11e9-935f-6549a3de3fbe.png)

MS-DOS Player
![2](https://user-images.githubusercontent.com/29886853/65024785-1691f080-d968-11e9-847e-8abcd8c09e1c.png)

**Comment by leecher1337** [comment]
Ad 1)
 * With original NTVDM with V86 on 32bit Windows, the operation takes approx. 4 seconds
 * With HAXM accelleration, the operation takes approx. 12 seconds
 * With CCPU or DOSBOX/VDOS emulator, the operation takes over 1 minute

Ad 2)
I once had a look at the FPU code and the MSDOSplayer FPU implementation seems to be incomplete according to sourcecode comments (x87ops.c has a lot of FIXME and TODO in header). 
The CCPU FPU implementation seems to be nearly complete, but may be slower due to this (fpu.c). This it too complicated for me to optimize, but if someone with enough knowledge can take a look, it would be benificial of course.
Regarding Video performance, I think rewriting the CVIDC was the maximum that I could do for it.

Here are my Landmark results for CCPU:
![landmark-1](https://user-images.githubusercontent.com/6495842/65034264-f6056e80-d946-11e9-909a-3437f5f6922a.jpg)

For HAXM, the results are quite odd, but I knew that already, it may be related to some timing issue or whatever. Well, it's just experimental anyway:

![landmark-2](https://user-images.githubusercontent.com/6495842/65034315-159c9700-d947-11e9-8a48-6db05bcb75ba.jpg)

**Comment by peter8777555** [comment]
Wow ! The HAXM/CCPU over 6 times operation.
My PC has use for 10 years and PC is too old.

Thank you for creating NTVDMX64 project.
It is very nice for me.

I use NTVDMX64/MS-DOS Player/QEMU/DosBox/WineVDM/VMWare/......
