### ISSUE TITLE
About v7vga.rom

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#63]
I find a rom.
It can replace v7vga.rom with the rom ??

**Comment by leecher1337** [comment]
If you are planning to improve VGA capabilities with it, I have to disappoint you.
Graphic capabilities need to be implemented in the VGA Emulation code of NTVDM.
The classic NTVDM on x32 uses the system VGA ROM, because it is using the VGA card directly and therefore needs to access it via the correct BIOS.
However starting with Windows 8, the XPDDM display driver model was deprecated and the support for direct VGA card access went away with it. That's the reason why you can't switch to fullscreen with ALT+RETURN anymore on Windows 8 or higher. This may be due to the fact, that the video output is now done via the GPU and there may not be a way to switch between VGA mode and accellerated GPU mode, but that's just my speculation on why this feature was removed.

This NTVDMx64 just uses the lousy VGA emulation that came with the SoftPC, and VESA wasn't available back in 1989 when SoftPC was written.
So the short answer: No, you won't benefit from another ROM on NTVDMx64, sorry

**Comment by peter8777555** [comment]
OK.
Thank you for detail info.
