### ISSUE TITLE
About MinNT

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#65]
About MinNT

1.
There are many Windows PE on the internet.
The Windows PE are more powerful.
Why need the MinNT ?

2.
Windows Driver Kit Version 7.1.0 
Microsoft Windows SDK for Windows 7 and .NET Framework 4 (ISO) 

If i need NTVDMX64 only,do i need those files ?

Thank you.

**Comment by leecher1337** [comment]
1. The name may be misleading, this is not a Windows PE component. As stated in the minnt.txt, it's a build system developed by @stephanosio that tries to replace the classic NT build system having the advantage that you don't need to have a fixed drive letter for building and you don't need to prebuild parts of the NT kernel for compilation (no bld-ntos.cmd needed), as it already contains then necessary libs. 

2. These kits are needed, because some header, .lib and .dll files are missing in the MinNT repository. The good news is, that you don't need to install anything on your dev-machine, as can be seen by the prepare.cmd, you just need the ISOs where the required files get pulled out and applied to MinNT repository (you can delete them after prepare.cmd runs through successfully). This is required mainly for legal reasons. The EULA for the SDK and DDK states, that you are not allowed to redistribute files from it, therefore I cannot put them into my repository. So you need to go the long route and let the prepare.cmd extract them from the .ISO for you.

Still, at the current state, patches haven't been ported to MinNT, so you still won't be able to build the NTVDM (without patches, it wants to build the MONITOR v86 version which fails on assembling), but I hope that as soon as I port the patches to it, we may be able to get a NTVDMx64 with a newer sourcecode base that is more closely to the NTVDM that is in use by recent Windows versions.

I hope that answers your questions so far.

**Comment by peter8777555** [comment]
OK,it is very clear.

GOOD NEWS:
you don't need to install anything on your dev-machine, 
as can be seen by the prepare.cmd, you just need the ISOs 
where the required files get pulled out and applied to MinNT repository

I like this new news.

Thank you for good project.

**Comment by leecher1337** [comment]
Well, I lied.. You need 7-zip installed to unpack the stuff, but it is a useful utility anyway ;-)
Will add this information to minnt.txt on next commit.

I'm planning to split repository patchsets into minnt and old-src patchset, so nothing will be lost, but haven't decided if I will continue to support old-src tree. If minnt tree works as expected, new patchsets most likely will only be in minnt tree, but contributors can always port them to old-src and send pull-requests, it's trivial to port the patches, in most cases just the offsets within the patch file need to be adjusted accordingly.

**Comment by peter8777555** [comment]
7-Zip is my sweet heart tool -:D

Support your idea.
If the new patchsets are more better,i support your idea.

**Comment by peter8777555** [comment]
I have questions.

1.
What is different about the MinNT and OpenNT ?

OpenNT:
The main goal of this project is to produce fully functional Windows NT builds 
for x86, MIPS, Alpha and PowerPC architectures for legacy systems, as well as 
to add new features implemented in modern NT operating systems to the NT 4 source tree (hence, NT 4.5).

So,does the OpenNT is a FULL OS ?
I can normal install to PC.

MinNT:
Mini NT ?
What is the main goal ?

2.
The MinNT/OpenNT base on NT 4 source tree.
The NT4 build for "x86" build in NTVDM,it "orginal" can support 16-bit programs.
I confuse your NTVDMX64 and origal NTVDM.
I know the NTVDMX64 with more enhance features.

**Comment by stephanosio** [comment]
Just to clarify what's what:

OpenNT: the name of the project that no longer exists

old-src: the original hack-job to build the leaked NT 4 source code as is with minimal amount of changes; it comes with its own build environment. I referred to it as old/obsolete because the original plan was to get all the components refactored into the MinNT and other component-specific repositories, as the original NT 4 source tree is just a big mess.

MinNT (Minimal NT): initiative to isolate only the essential core components (such as kernel and subsystems) out of the leaked NT 4 source code and refactor them to NT 5.1-esque source tree; the MinNT repository does not come with its own build environment and uses NTOSBE as its build environment.

NTOSBE (NT Operating System Build Environment): the unified build environment for OpenNT Project. The main goal was to provide single unified build environment that can be used to build all OpenNT components (not including then-declared-obsolete old-src, of course).

**Comment by peter8777555** [comment]
To : stephanosio

Thank you for detail info.

**Comment by peter8777555** [comment]
minnt.txt

equirements

 * MinNT repository with NTVDM with latest commits as of Apr 16, 2017 
   (q160765803-minint4-85fac4faadc7)
   opennt.net site contains some hints on where to find it.

==> It seem need more and more hints and LUCKY to find it.

![zz1](https://user-images.githubusercontent.com/29886853/66497692-6e4af400-eaef-11e9-9e74-ab32173c0d88.png)

![zz2](https://user-images.githubusercontent.com/29886853/66497693-6e4af400-eaef-11e9-892f-782f9fcf29f7.png)

**Comment by stephanosio** [comment]
http://file.opennt.net/release/snapshot/MinNT-20170416-85fac4faadc77203db8ddc66af280a75c1b717b0.zip

**Comment by peter8777555** [comment]
To : stephanosio

Thank you.

**Comment by peter8777555** [comment]
To: leecher1337

leecher1337 : q160765803-minint4-85fac4faadc7
stephanosio : MinNT-20170416-85fac4faadc77203db8ddc66af280a75c1b717b0.zip

Both of them are the same ??

It likes HASH
85fac4faadc7
85fac4faadc77203db8ddc66af280a75c1b717b0

I try to MD5/SH1/SH256/SH384/SH512/ HASH,but NG.

Suggestion:
You can show the HASH,the users can confirm the correct version.

Thank you.

**Comment by leecher1337** [comment]
I can hereby confirm that the version posted above is exactly the version you need :-)

**Comment by peter8777555** [comment]
I have downloaded ALL files.

By the way,
GRMSDK_EN_DVD.iso
GRMWDK_EN_7600_1.ISO

Does it include multilingual(None English) ?

**Comment by leecher1337** [comment]
They are just needed for .lib files and .dlls required for building, language doesn't matter in this regard.
