### ISSUE TITLE
How about source code from NTVDM from Windows 2000 and later

### ISSUE THREAD

**Issue by WindowsNinetyTen** [leecher1337/ntvdmx64#72]
Why not incorporate source code from NTVDM from Windows 2000 or later as well?

**Comment by leecher1337** [comment]
You mean minnt repository #65 ?
I'm currently working on it, it requires different patches. It supports multilang, I guess that's the reason why you want to have it. However its DPMI implementation is broken for CCPU-Builds, so DPMI needs to be used from old-src repository.
Porting HAXM support to MINNT won't be done anytime soon, but the other patchsets for minnt are nearly ready.

**Comment by HomerBender77** [comment]
> I guess that's the reason why you want to have it.

I guess that one could say that. But the main reason is because I thought that source code from Windows 2000 and later would improve the accuracy of NTVDM. 

Also, I've just downloaded the ZIP with all the files to be compiled. But, under ntvdmpatch>release, there is also an INSTALL.BAT file. Would this file install NTVDMX64 with all the latest patches and updates?

**Comment by leecher1337** [comment]
Don't expect any improvements in accuracy, the main core of the softpc hasn't changed a lot between the versions. You get DOS LFN-Support and rudimentary SB 2.0 support (the stuff I tried to backport in the updates-Folder, before I found minnt source - would have saved me a lot of effort if I would have checked that before).
And you get multilanguage. The NEC98 support is also new, but I guess this is nothing that we can profit from, maybe far east language support got better too. 
And they removed swear words from the source and the "easteregg" in YODA, how lame! I actually made a patch to put them back in place again :-P
As the Win2k NTVDM didn't have to care about CCPU anymore, olny V86, as there were no more MIPS/ALPHA builds, there are quite some bugs in the source regarding that, which need to be fixed. And the DPMI host also doesn't seem to be compatible with CCPU anymore, that's why we still have to use the classic one.

The release directory is the template directory which contains all the files that get put into the final output directory after everything is compiled. So it's basically the installer the user runs when everything is in place. As noted in #7 most people can save themselves the hassle of compiling anyway, if they don't want to try the HAXM build ;-)
