### ISSUE TITLE
How to actually run applications? 

### ISSUE THREAD

**Issue by parkerlreed** [leecher1337/ntvdmx64#9]
I've been trying to get NTVDMx64 working. I have it installed (rebooted afterwards) and have been trying to run the original SkiiFree. https://ski.ihoc.net/ski.zip

No matter where I launch it from (Explorer, compatibility mode, cmd, elevated cmd), I get the usual not compatible message. ntvdm.exe by itself runs and exits (I believe as it should) so I'm not sure if I'm just missing something trying to run this.

This is on Windows 10 x64 OS build 15063.250

**Comment by leecher1337** [comment]
Seems like ldntvdm.dll loader library doesn't get loaded properly vi AppInit hook then or may have been deleted by some Antivirus solution or the symbol lookup fails due to a lack of proper Internet connection.
Please ensure using Process Explorer by Sysinternals that ldntvdm.dll is loaded into every process in your system by looking at the module list.
If this is the case, use DebugView by Sysinternals to check whether there are error messages sent by ldntvdm.dll. For instance, if you are on the Fast ring of the Windows 10 updates, symbols are often not evailable t the release date causing ldntvdm.dll to not be able to resolve the required symbols properly and therefore not working as expected.

**Comment by parkerlreed** [comment]
ldntvdm.dll is loaded in every process. 

When I try actually running 16bit from Explorer and get the "This app can't run on your PC" I do get 

[12236] NTVDM hook installed

In DebugView. No other errors regarding ldntvdm.dll

Also not in the fast ring.

**Comment by parkerlreed** [comment]
Just tried on another machine and get this trying to run ntvdm.exe directly (still doesn't run 16bit normally)

![capture](https://cloud.githubusercontent.com/assets/841440/25661235/ca78885c-2fdd-11e7-8482-78c55e322289.PNG)

**Comment by parkerlreed** [comment]
Ok I did a fresh start and reinstalled and cleared up that error. The original issue is also affecting this machine. Everything seems like it's in place but it just refuses to run.

**Comment by parkerlreed** [comment]
This computer is on the fast ring itself but exhibiting the exact same behavior as the one that isn't

![capture](https://cloud.githubusercontent.com/assets/841440/25662394/54fc0d06-2fe2-11e7-8700-639e7a0982d3.PNG)

**Comment by leecher1337** [comment]
Hi,
I'm currently using Build 14393. 
On the PC with the environment error message, did you check that ntvdm.exe also has ldntvdm.dll loaded? Coulde be that only the x64 version of the module gehts injected and not the x32 one, which is needed in order to get GetNextVdmCommand() API call working.

**Comment by leecher1337** [comment]
Here is a version of the ldntvdm libraries for x32 and x64 that output verbose info about the loader, which may help identifying potential problems when starting 16bit applications like mentioned above.
The output is given via DbgView and is prefixed with LDNTVDM:
https://github.com/leecher1337/ntvdmx64/releases/download/ldntvdm-dbg/ldntvdm.zip

**Comment by phly95** [comment]
I wonder if this program no longer works under the creators update and above? I'm on Creators update and I'm having the same issue. It may also be due to having smartscreen enabled.

**Comment by leecher1337** [comment]
As said,  I cannot help you with it if you don't check your debug logs using the build specified above
