### ISSUE TITLE
Prepare.cmd file prompts me to install 7-Zip German version even though I already have the English Installed and NTVDM still doesn't work

### ISSUE THREAD

**Issue by WindowsNinetyTen** [leecher1337/ntvdmx64#91]
Should I still download the German 7-Zip anyway?

**Comment by leecher1337** [comment]
The language version is irrelevant. The only point is that the 7z.exe should be reachable from commandline, thus, 7-zip is in PATH
The script was unable to execute 7z.exe which means that it's not in path.
You can try to patch the prepare.cmd in order to detect it from Registry. Please let me know if it works. If so, I'd update the prepare.cmd.
Please replace the lines
```
7z >nul 2>&1
if errorlevel 255 (
echo Please install 7zip first, then run again
start http://www.7-zip.de
pause
goto fini
)
```

with

```
7z >nul 2>&1
if errorlevel 255 (
for /F "skip=2 tokens=3*" %%r in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\7-zip" /v Path') do echo set PATH=%PATH%;%%r
7z >nul 2>&1
if errorlevel 255 (
echo Please install 7zip first, then run again
start http://www.7-zip.de
pause
goto fini
)
)
```

That should query the 7Z path from registry as a fallback and put it in PATH.

**Comment by HomerBender77** [comment]
Never mind. I found the problem. However, after installation neither NTVDM nor any DOS programs work. They just show up black and then close. Also, during the bld-minnt.cmd process, I get a message at one point saying "This app can't run on your PC" and the end result is only 813 files binplaced, instead of 815,

**Comment by HomerBender77** [comment]
![bildo](https://user-images.githubusercontent.com/45469534/82520950-57439a00-9af3-11ea-8527-69ff224f34db.png)

**Comment by leecher1337** [comment]
Could it be that you have some DOS-utilities with the same name in your PATH which have a higher priority than the SDK tools shipped with NTOSbe? There was a similar issue here #76 

You can attach your buildchk.log and buildchk.err here, for further analysis, but first check your path. 
Regardign the loader, ensure that you isntalled it correctly and that no Antivirus application etc. deleted it after installation. See #89

**Comment by HomerBender77** [comment]
I tried to follow the directions in the minnt readme file.

**Comment by leecher1337** [comment]
Good for you, but can you please check the things I mentioned above, otherwise I won't be able to help you.

**Comment by leecher1337** [comment]
As you still haven't provided the requested logfiles, can I assume the problem as solved and close the issue?

**Comment by HomerBender77** [comment]
Oh. Sorry about the lack of reply. I have been busy with work for college. I will provide the files as soon as possible.

**Comment by HomerBender77** [comment]
[buildchk.log](https://github.com/leecher1337/ntvdmx64/files/4709093/buildchk.log)
Here is the buildchk.log file.
[buildchk.zip](https://github.com/leecher1337/ntvdmx64/files/4709099/buildchk.zip)
Here is the buildchk.err file in a zip folder. I had to put it in a zip folder because the message bard does not directly support .err files.

**Comment by leecher1337** [comment]
Can you attach your c:\WORK\minnt\base\mvdm\softpc.new\host\inc\nt_reset.h here? 
Maybe it got patched twice for whatever reason and got destroyed by it?

Also: Did you download the most recent ntvdmpatch released just a few days ago and the most recent NTOSBE from stephanos' repository? Just asking, because I tested this combination just recently before releasing, so I have proof that it works here and we have the same build to verify.

**Comment by HomerBender77** [comment]
[nt_reset.zip](https://github.com/leecher1337/ntvdmx64/files/4720075/nt_reset.zip)

**Comment by leecher1337** [comment]
The ```#ifdef X86GFX``` in your nt_reset.h is in there twice, so the file got patched twice instead of only once.
As there is only one .patch file modifying the file, an error in the patchset can be ruled out.
Please verify your build steps and ensure that you didn't run the patch.cmd twice and that you start off with a clean copy of minnt, because it looks like either your minnt-source is not clean or the patch gets applied more than once. A clean nt_reset.h doesn't contain the ```#ifdef X86GFX```line, this gets added by patch.

**Comment by HomerBender77** [comment]
I did run it twice. And I did it because I had the same problem of NTVDM flashing and then closing, even after following the steps for the first time.

**Comment by leecher1337** [comment]
Waht output do you see in [DebugView ](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) on start of ntvdm?

**Comment by HomerBender77** [comment]
How can I see DebugView?

**Comment by leecher1337** [comment]
Check that Capture/Capture Win32 is checked

**Comment by HomerBender77** [comment]
Should I look in the WORK directory?

**Comment by leecher1337** [comment]
I thought you have problems starting ntvdm.exe, so that is closes immediately. 
Start debugview, start DOS application, check log displayed in debugview.

**Comment by HomerBender77** [comment]
I have problems starting NTVDM or any DOS application.

**Comment by leecher1337** [comment]
So what's your DebugView output then?

**Comment by HomerBender77** [comment]
I don't know how to get there.

**Comment by leecher1337** [comment]
Oh dear... I mean, srsly...?

1) Download DebugView.zip
2) Unzip DebugView.zip
3) Doubleclick on Dbgview.exe

**Comment by HomerBender77** [comment]
[NTVDM.LOG](https://github.com/leecher1337/ntvdmx64/files/4767776/NTVDM.LOG)

**Comment by HomerBender77** [comment]
Here's the log.

**Comment by leecher1337** [comment]
It seems that NTVDM initializes correctly by checking, if iti is the first VDM, but then silently dies without raising an error. Can you check your Windows Application log if there are traces of a crash of NTVDM.EXE?

**Comment by leecher1337** [comment]
No feedback has been given within 18 months, assuming that problem got resolved in the meantime with newer NTVDM builds.
